name: quiz
description: "IQ Easy Quiz"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  ionicons: ^0.2.2
  flutter_feather_icons: ^2.0.0+1
  eva_icons_flutter: ^3.0.2
  remixicon: ^1.4.1
  phosphor_flutter: ^2.0.0
  flutter_tabler_icons: ^1.0.0
  bootstrap_icons: ^1.11.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter_native_splash:
  background_image: "assets/icons/splash_screen.png"
  fullscreen: true
  android_12:
    icon_background_color: "#ffffff"
    background_image: "assets/icons/splash_screen.png"
    
    fullscreen: true
  android: true
  ios: true

